#!/bin/sh

# Non bspwm stuff
# set background
# feh --bg-scale --no-fehbg ~/Pictures/wallpapers/kogecha/1610795520895.jpg
feh --bg-fill --no-fehbg ~/Pictures/wallpapers/blood_trees.png

# merge Xresources
xrdb -merge ~/.Xresources

# Program launches to start
# picom &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.local/source/eww/target/release/eww open bar &
# $HOME/.config/polybar/launch.sh &

# bspc subscribe node_state | while read -r _ _ _ _ state flag; do
#   if [[ "$state" != fullscreen ]]; then continue; fi
#   if [[ "$flag" == on ]]; then
#     xdotool search --class eww-bar windowunmap
#   else
#     xdotool search --class eww-bar windowmap
#   fi
# done &
# $HOME/.config/polybar/launch.sh &


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focused_border_color "#ebddb2"
# bspc config focused_border_color "#CC241D"
# bspc config focused_border_color "#D79921"
# bspc config focused_border_color "#458588"


bspc config border_width         1
bspc config window_gap          10


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled 
bspc rule -a Files state=floating
bspc rule -a kitty:R state=floating center=on rectangle=1920x1080+0+0
