#!/bin/sh

# Non bspwm stuff
# set background
feh --bg-scale --no-fehbg ~/Pictures/wallpapers/kogecha/1610795520895.jpg

# merge Xresources
xrdb -merge ~/.Xresources

# Program launches to start
# picom &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &


bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config focused_border_color "#CC241D"
# bspc config focused_border_color "#D79921"
# bspc config focused_border_color "#458588"


bspc config border_width         4
bspc config window_gap          30


bspc config split_ratio          0.54
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Settings manage=off
bspc rule -a Spotify state=floating
bspc rule -a Zathura state=tiled 
bspc rule -a discord state=pseudo_tiled
bspc rule -a Files state=floating
